--------------------------------------------------------------------------------
-- 01_schema.sql  —  Multi-tenant service desk: 13-table core schema (APEX 26.1)
--------------------------------------------------------------------------------
-- Source of truth: docs/ticketing-system-brief.md  (§ data model, design locked
-- 2026-07-04: projects layer, named SLA policies, per-project agent tiers).
-- Conventions honoured here:
--   * UPPER_SNAKE_CASE objects; IDENTITY primary keys.
--   * TIMESTAMP WITH LOCAL TIME ZONE on every timestamp (enables aging/FRT/SLA
--     metrics with no schema change — brief §data-model rule 1).
--   * TICKET_HISTORY.action is a fixed enum, not free text (rule 3).
--   * TICKETS.company_id is THE tenant key — every client-facing query filters it.
--   * TICKETS.project_id scopes to the service engagement (decision O); the
--     composite FK to PROJECTS makes a cross-tenant project reference impossible.
-- Run order: 00_drop_all (optional reset) -> 01_schema -> 02_seed_data.
--------------------------------------------------------------------------------

-- Sequence that feeds the human-readable ticket reference.
-- Seeded tickets carry the mockup refs (TKT-00019 … TKT-00053), so live tickets start at 54.
CREATE SEQUENCE TICKET_REF_SEQ START WITH 54 INCREMENT BY 1 NOCACHE;

--------------------------------------------------------------------------------
-- COMPANIES — every company (the service provider and its customers are all tenants).
--------------------------------------------------------------------------------
CREATE TABLE COMPANIES (
  COMPANY_ID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  COMPANY_NAME  VARCHAR2(200)  NOT NULL,
  STATUS        VARCHAR2(10)   DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT COMPANIES_PK       PRIMARY KEY (COMPANY_ID),
  CONSTRAINT COMPANIES_NAME_UK  UNIQUE (COMPANY_NAME),
  CONSTRAINT COMPANIES_STAT_CK  CHECK (STATUS IN ('ACTIVE','INACTIVE'))
);

--------------------------------------------------------------------------------
-- DEPARTMENTS — departments within a company. METADATA ONLY (decision N revised):
-- used for routing/reporting, never for visibility scoping.
--------------------------------------------------------------------------------
CREATE TABLE DEPARTMENTS (
  DEPARTMENT_ID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  COMPANY_ID       NUMBER         NOT NULL,
  DEPARTMENT_NAME  VARCHAR2(200)  NOT NULL,
  CONSTRAINT DEPARTMENTS_PK      PRIMARY KEY (DEPARTMENT_ID),
  CONSTRAINT DEPARTMENTS_COMP_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES (COMPANY_ID),
  CONSTRAINT DEPARTMENTS_UK      UNIQUE (COMPANY_ID, DEPARTMENT_NAME),
  -- Composite-FK target so USER/TICKET department references can't cross tenants:
  CONSTRAINT DEPARTMENTS_COMP_UK UNIQUE (DEPARTMENT_ID, COMPANY_ID)
);

--------------------------------------------------------------------------------
-- APP_USERS — everyone who logs in; company drives tenant context.
-- ROLE moved to USER_ROLES (multi-role support, decision P).
-- Tier is NOT here — it lives on AGENT_PROJECTS (per-project tier, decision M
-- revised 2026-07-04: one agent can be L3 on one engagement, L1 on another).
--------------------------------------------------------------------------------
CREATE TABLE APP_USERS (
  USER_ID        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  COMPANY_ID     NUMBER         NOT NULL,
  DEPARTMENT_ID  NUMBER,                          -- nullable: vendor staff may not need one
  FULL_NAME      VARCHAR2(200)  NOT NULL,
  EMAIL          VARCHAR2(255)  NOT NULL,
  DEFAULT_ROLE   VARCHAR2(20),                    -- landing role at login; NULL = highest-privilege from USER_ROLES
  STATUS         VARCHAR2(10)   DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT APP_USERS_PK       PRIMARY KEY (USER_ID),
  CONSTRAINT APP_USERS_EMAIL_UK UNIQUE (EMAIL),
  CONSTRAINT APP_USERS_COMP_FK  FOREIGN KEY (COMPANY_ID)    REFERENCES COMPANIES (COMPANY_ID),
  -- Composite FK: a user's department must belong to the user's own company.
  -- (Enforced only when DEPARTMENT_ID is set — NULL department stays allowed.)
  CONSTRAINT APP_USERS_DEPT_FK  FOREIGN KEY (DEPARTMENT_ID, COMPANY_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID, COMPANY_ID),
  CONSTRAINT APP_USERS_STAT_CK  CHECK (STATUS IN ('ACTIVE','INACTIVE'))
);
CREATE INDEX APP_USERS_COMP_IX ON APP_USERS (COMPANY_ID);
CREATE INDEX APP_USERS_DEPT_IX ON APP_USERS (DEPARTMENT_ID);

--------------------------------------------------------------------------------
-- USER_ROLES — one-to-many roles per user (decision P: multi-role support).
-- Replaces APP_USERS.ROLE. A user must have at least one row (enforced by app).
-- Enables role-switching in the nav bar without re-login. Every provider-company
-- user is auto-granted CLIENT_USER at creation (decision Q).
--------------------------------------------------------------------------------
CREATE TABLE USER_ROLES (
  USER_ID  NUMBER       NOT NULL,
  ROLE     VARCHAR2(20) NOT NULL,
  CONSTRAINT USER_ROLES_PK      PRIMARY KEY (USER_ID, ROLE),
  CONSTRAINT USER_ROLES_U_FK    FOREIGN KEY (USER_ID) REFERENCES APP_USERS (USER_ID),
  CONSTRAINT USER_ROLES_ROLE_CK CHECK (ROLE IN ('CLIENT_USER','CLIENT_ADMIN','SUPPORT_AGENT','SYSTEM_ADMIN'))
);

--------------------------------------------------------------------------------
-- SLA_POLICIES — named SLA tiers (Gold/Standard/Bronze/Internal, decision S).
-- Projects are ASSIGNED a policy; exactly one policy is the IS_DEFAULT fallback
-- for projects with no assignment (enforced by the function-based unique index).
--------------------------------------------------------------------------------
CREATE TABLE SLA_POLICIES (
  SLA_POLICY_ID   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  POLICY_NAME     VARCHAR2(100)  NOT NULL,
  IS_DEFAULT      CHAR(1)        DEFAULT 'N' NOT NULL,
  DESCRIPTION     VARCHAR2(500),
  EFFECTIVE_FROM  DATE,                            -- ISO 20000 §8.6.3 documentation
  APPROVED_BY     NUMBER,                          -- who signed the policy off
  NOTES           VARCHAR2(1000),
  CONSTRAINT SLA_POLICIES_PK       PRIMARY KEY (SLA_POLICY_ID),
  CONSTRAINT SLA_POLICIES_NAME_UK  UNIQUE (POLICY_NAME),
  CONSTRAINT SLA_POLICIES_APPR_FK  FOREIGN KEY (APPROVED_BY) REFERENCES APP_USERS (USER_ID),
  CONSTRAINT SLA_POLICIES_DEF_CK   CHECK (IS_DEFAULT IN ('Y','N'))
);
-- At most ONE default policy: only 'Y' rows are indexed, and they must be unique.
CREATE UNIQUE INDEX SLA_POLICIES_ONEDEF_UX
  ON SLA_POLICIES (CASE WHEN IS_DEFAULT = 'Y' THEN 'Y' END);

--------------------------------------------------------------------------------
-- SLA_TARGETS — per-severity target rows PER POLICY (FR-23, decision S).
-- Re-keyed from (company_id, severity) to (sla_policy_id, severity).
--------------------------------------------------------------------------------
CREATE TABLE SLA_TARGETS (
  SLA_TARGET_ID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  SLA_POLICY_ID    NUMBER         NOT NULL,
  SEVERITY         VARCHAR2(10)   NOT NULL,
  RESPONSE_HOURS   NUMBER,                        -- target first-response time in hours (FR-31)
  RESOLUTION_DAYS  NUMBER         NOT NULL,       -- target resolution time in days
  ESCALATION_PCT   NUMBER         DEFAULT 80,     -- FR-35: % of SLA elapsed that triggers auto-escalation
  CONSTRAINT SLA_TARGETS_PK      PRIMARY KEY (SLA_TARGET_ID),
  CONSTRAINT SLA_TARGETS_POL_FK  FOREIGN KEY (SLA_POLICY_ID) REFERENCES SLA_POLICIES (SLA_POLICY_ID),
  CONSTRAINT SLA_TARGETS_SEV_CK  CHECK (SEVERITY IN ('Critical','Major','Minor','Low')),
  CONSTRAINT SLA_TARGETS_UK      UNIQUE (SLA_POLICY_ID, SEVERITY)
);

--------------------------------------------------------------------------------
-- PROJECTS — service engagements per company (decision O).
-- PROJECT_KEY is globally unique + company-prefixed (e.g. ACME-IT, decision S).
-- VISIBILITY: OPEN = whole company sees it; RESTRICTED = invitation-only via
-- USER_PROJECTS (decision Q). SLA_POLICY_ID NULL = the IS_DEFAULT policy applies.
-- PROJECTS_COMP_UK exists so TICKETS can carry a composite FK (project, company)
-- — a ticket physically cannot reference another company's project.
--------------------------------------------------------------------------------
CREATE TABLE PROJECTS (
  PROJECT_ID     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  COMPANY_ID     NUMBER         NOT NULL,
  PROJECT_NAME   VARCHAR2(200)  NOT NULL,
  PROJECT_KEY    VARCHAR2(10)   NOT NULL,
  SLA_POLICY_ID  NUMBER,
  DESCRIPTION    VARCHAR2(500),
  VISIBILITY     VARCHAR2(10)   DEFAULT 'OPEN' NOT NULL,
  IS_ACTIVE      CHAR(1)        DEFAULT 'Y' NOT NULL,
  CREATED_AT     TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PROJECTS_PK       PRIMARY KEY (PROJECT_ID),
  CONSTRAINT PROJECTS_KEY_UK   UNIQUE (PROJECT_KEY),
  CONSTRAINT PROJECTS_NAME_UK  UNIQUE (COMPANY_ID, PROJECT_NAME),
  CONSTRAINT PROJECTS_COMP_UK  UNIQUE (PROJECT_ID, COMPANY_ID),
  CONSTRAINT PROJECTS_COMP_FK  FOREIGN KEY (COMPANY_ID)    REFERENCES COMPANIES (COMPANY_ID),
  CONSTRAINT PROJECTS_SLA_FK   FOREIGN KEY (SLA_POLICY_ID) REFERENCES SLA_POLICIES (SLA_POLICY_ID),
  CONSTRAINT PROJECTS_VIS_CK   CHECK (VISIBILITY IN ('OPEN','RESTRICTED')),
  CONSTRAINT PROJECTS_ACT_CK   CHECK (IS_ACTIVE IN ('Y','N'))
);
CREATE INDEX PROJECTS_COMP_IX ON PROJECTS (COMPANY_ID);

--------------------------------------------------------------------------------
-- CATEGORIES — hybrid scope (brief §5): COMPANY_ID NULL = global/standard
-- category; set = company-specific. PROJECT_ID NULL = all projects of that
-- company (or global); set = project-specific. DESCRIPTION is the guidance
-- text shown in the category LOV (FR-34 pattern).
--------------------------------------------------------------------------------
CREATE TABLE CATEGORIES (
  CATEGORY_ID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  CATEGORY_NAME  VARCHAR2(100) NOT NULL,
  COMPANY_ID     NUMBER,
  PROJECT_ID     NUMBER,
  DESCRIPTION    VARCHAR2(500),
  CONSTRAINT CATEGORIES_PK        PRIMARY KEY (CATEGORY_ID),
  CONSTRAINT CATEGORIES_COMP_FK   FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES (COMPANY_ID),
  -- Composite FK: a project-specific category's project must belong to the same
  -- company (enforced only when PROJECT_ID is set; SCOPE_CK forces COMPANY_ID then).
  CONSTRAINT CATEGORIES_PROJ_FK   FOREIGN KEY (PROJECT_ID, COMPANY_ID) REFERENCES PROJECTS (PROJECT_ID, COMPANY_ID),
  CONSTRAINT CATEGORIES_SCOPE_CK  CHECK (PROJECT_ID IS NULL OR COMPANY_ID IS NOT NULL)
);
-- Uniqueness must collapse the NULL scope columns: a plain composite UNIQUE is
-- silently ineffective in Oracle when any column is NULL (duplicate global names
-- would be allowed). NVL(-1) makes 'one global Network / one per scope' real.
CREATE UNIQUE INDEX CATEGORIES_NAME_SCOPE_UX
  ON CATEGORIES (UPPER(CATEGORY_NAME), NVL(COMPANY_ID, -1), NVL(PROJECT_ID, -1));

--------------------------------------------------------------------------------
-- AGENT_PROJECTS — which projects each agent covers AND AT WHAT TIER
-- (decisions I + M revised 2026-07-04: tier is per agent-project mapping —
-- one agent can be L3 on one engagement and L1 on another).
-- Replaces AGENT_COMPANIES. All tier checks evaluate on the ticket's project.
--------------------------------------------------------------------------------
CREATE TABLE AGENT_PROJECTS (
  USER_ID     NUMBER       NOT NULL,
  PROJECT_ID  NUMBER       NOT NULL,
  TIER        VARCHAR2(5)  NOT NULL,
  CONSTRAINT AGENT_PROJECTS_PK       PRIMARY KEY (USER_ID, PROJECT_ID),
  CONSTRAINT AGENT_PROJECTS_U_FK     FOREIGN KEY (USER_ID)    REFERENCES APP_USERS (USER_ID),
  CONSTRAINT AGENT_PROJECTS_P_FK     FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (PROJECT_ID),
  CONSTRAINT AGENT_PROJECTS_TIER_CK  CHECK (TIER IN ('L1','L2','L3','L4'))
);
CREATE INDEX AGENT_PROJECTS_P_IX ON AGENT_PROJECTS (PROJECT_ID);

--------------------------------------------------------------------------------
-- USER_PROJECTS — INVITATION list into Restricted projects (decision Q).
-- Rows GRANT access, never restrict: a client user sees all OPEN projects of
-- their company automatically, plus any RESTRICTED project listed here.
-- Managed by the Client Admin.
--------------------------------------------------------------------------------
CREATE TABLE USER_PROJECTS (
  USER_ID     NUMBER  NOT NULL,
  PROJECT_ID  NUMBER  NOT NULL,
  CONSTRAINT USER_PROJECTS_PK    PRIMARY KEY (USER_ID, PROJECT_ID),
  CONSTRAINT USER_PROJECTS_U_FK  FOREIGN KEY (USER_ID)    REFERENCES APP_USERS (USER_ID),
  CONSTRAINT USER_PROJECTS_P_FK  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (PROJECT_ID)
);
CREATE INDEX USER_PROJECTS_P_IX ON USER_PROJECTS (PROJECT_ID);

--------------------------------------------------------------------------------
-- TICKETS — the support requests. company_id is the tenant key; project_id
-- scopes to the service engagement (decision O). The composite FK
-- (PROJECT_ID, COMPANY_ID) guarantees the ticket's tenant always matches its
-- project's tenant — a cross-company project reference cannot be inserted.
--------------------------------------------------------------------------------
CREATE TABLE TICKETS (
  TICKET_ID           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  TICKET_REF          VARCHAR2(20)   NOT NULL,
  COMPANY_ID          NUMBER         NOT NULL,
  PROJECT_ID          NUMBER         NOT NULL,     -- service engagement (decision O)
  DEPARTMENT_ID       NUMBER,                      -- stamped from creator's department (metadata, decision N revised)
  TICKET_TYPE         VARCHAR2(20)   DEFAULT 'INCIDENT' NOT NULL,
  SUBJECT             VARCHAR2(300)  NOT NULL,
  DESCRIPTION         CLOB,
  CATEGORY_ID         NUMBER         NOT NULL,     -- required at creation (ITIL categorization)
  SEVERITY            VARCHAR2(10)   NOT NULL,     -- client-set: Critical/Major/Minor/Low
  PRIORITY            VARCHAR2(5),                 -- support-set: P1-P4, nullable until triaged (FR-37)
  STATUS              VARCHAR2(20)   DEFAULT 'New' NOT NULL,
  CREATED_BY          NUMBER         NOT NULL,
  ASSIGNED_TO         NUMBER,
  CREATED_AT          TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT          TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  FIRST_RESPONSE_AT   TIMESTAMP WITH LOCAL TIME ZONE,   -- FR-31: stamped on first agent response
  RESOLVED_AT         TIMESTAMP WITH LOCAL TIME ZONE,
  CLOSED_AT           TIMESTAMP WITH LOCAL TIME ZONE,
  SLA_DUE_DATE        TIMESTAMP WITH LOCAL TIME ZONE,   -- stamped at creation from the project's SLA policy (default policy if none assigned)
  RESOLUTION_CODE     VARCHAR2(30),                      -- FR-36: required on Resolve
  RESOLUTION_SUMMARY  VARCHAR2(4000),                    -- FR-36: required on Resolve
  REOPEN_COUNT        NUMBER         DEFAULT 0 NOT NULL, -- incremented on Reopen
  CSAT_SCORE          NUMBER,                            -- FR-27: one-time, set at closure
  CONSTRAINT TICKETS_PK        PRIMARY KEY (TICKET_ID),
  CONSTRAINT TICKETS_REF_UK    UNIQUE (TICKET_REF),
  CONSTRAINT TICKETS_COMP_FK   FOREIGN KEY (COMPANY_ID)    REFERENCES COMPANIES (COMPANY_ID),
  CONSTRAINT TICKETS_PROJ_FK   FOREIGN KEY (PROJECT_ID, COMPANY_ID) REFERENCES PROJECTS (PROJECT_ID, COMPANY_ID),
  CONSTRAINT TICKETS_DEPT_FK   FOREIGN KEY (DEPARTMENT_ID, COMPANY_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID, COMPANY_ID),
  CONSTRAINT TICKETS_CAT_FK    FOREIGN KEY (CATEGORY_ID)   REFERENCES CATEGORIES (CATEGORY_ID),
  CONSTRAINT TICKETS_CBY_FK    FOREIGN KEY (CREATED_BY)    REFERENCES APP_USERS (USER_ID),
  CONSTRAINT TICKETS_ATO_FK    FOREIGN KEY (ASSIGNED_TO)   REFERENCES APP_USERS (USER_ID),
  CONSTRAINT TICKETS_TYPE_CK   CHECK (TICKET_TYPE IN ('INCIDENT','SERVICE_REQUEST')),
  CONSTRAINT TICKETS_SEV_CK    CHECK (SEVERITY IN ('Critical','Major','Minor','Low')),
  CONSTRAINT TICKETS_PRIO_CK   CHECK (PRIORITY IS NULL OR PRIORITY IN ('P1','P2','P3','P4')),
  CONSTRAINT TICKETS_STAT_CK   CHECK (STATUS IN ('New','Assigned','In Progress','On Hold','Resolved','Closed')),
  CONSTRAINT TICKETS_RCODE_CK  CHECK (RESOLUTION_CODE IS NULL OR RESOLUTION_CODE IN
      ('FIXED','WORKAROUND','KNOWN_ERROR','CANNOT_REPRODUCE','DUPLICATE','USER_EDUCATION','NOT_AN_INCIDENT')),
  CONSTRAINT TICKETS_CSAT_CK   CHECK (CSAT_SCORE BETWEEN 1 AND 5)
);
CREATE INDEX TICKETS_COMP_IX   ON TICKETS (COMPANY_ID);
CREATE INDEX TICKETS_PROJ_IX   ON TICKETS (PROJECT_ID);
CREATE INDEX TICKETS_DEPT_IX   ON TICKETS (DEPARTMENT_ID);
CREATE INDEX TICKETS_ATO_IX    ON TICKETS (ASSIGNED_TO);
CREATE INDEX TICKETS_STATUS_IX ON TICKETS (STATUS);

-- Auto-populate the human-readable reference on insert (TKT-00054, ...).
CREATE OR REPLACE TRIGGER TICKETS_REF_BI
  BEFORE INSERT ON TICKETS
  FOR EACH ROW
  WHEN (NEW.TICKET_REF IS NULL)
BEGIN
  :NEW.TICKET_REF := 'TKT-' || LPAD(TICKET_REF_SEQ.NEXTVAL, 5, '0');
END;
/

--------------------------------------------------------------------------------
-- TICKET_COMMENTS — the conversation. is_internal hides agent notes from clients.
--------------------------------------------------------------------------------
CREATE TABLE TICKET_COMMENTS (
  COMMENT_ID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  TICKET_ID     NUMBER NOT NULL,
  USER_ID       NUMBER NOT NULL,
  COMMENT_TEXT  CLOB   NOT NULL,
  IS_INTERNAL   CHAR(1) DEFAULT 'N' NOT NULL,
  CREATED_AT    TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT TICKET_COMMENTS_PK      PRIMARY KEY (COMMENT_ID),
  CONSTRAINT TICKET_COMMENTS_TKT_FK  FOREIGN KEY (TICKET_ID) REFERENCES TICKETS (TICKET_ID),
  CONSTRAINT TICKET_COMMENTS_USR_FK  FOREIGN KEY (USER_ID)   REFERENCES APP_USERS (USER_ID),
  CONSTRAINT TICKET_COMMENTS_INT_CK  CHECK (IS_INTERNAL IN ('Y','N'))
);
CREATE INDEX TICKET_COMMENTS_TKT_IX ON TICKET_COMMENTS (TICKET_ID);

--------------------------------------------------------------------------------
-- TICKET_HISTORY — audit trail. action is a FIXED enum (brief rule 3).
-- USER_ID is NOT NULL: system-driven actions use a designated system user.
--------------------------------------------------------------------------------
CREATE TABLE TICKET_HISTORY (
  HISTORY_ID   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  TICKET_ID    NUMBER NOT NULL,
  USER_ID      NUMBER NOT NULL,
  ACTION       VARCHAR2(20) NOT NULL,
  OLD_VALUE    VARCHAR2(200),
  NEW_VALUE    VARCHAR2(200),
  CREATED_AT   TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT TICKET_HISTORY_PK      PRIMARY KEY (HISTORY_ID),
  CONSTRAINT TICKET_HISTORY_TKT_FK  FOREIGN KEY (TICKET_ID) REFERENCES TICKETS (TICKET_ID),
  CONSTRAINT TICKET_HISTORY_USR_FK  FOREIGN KEY (USER_ID)   REFERENCES APP_USERS (USER_ID),
  CONSTRAINT TICKET_HISTORY_ACT_CK  CHECK (ACTION IN
      ('STATUS_CHANGE','ASSIGN','REASSIGN','ESCALATION','PRIORITY_CHANGE',
       'SEVERITY_CHANGE','CATEGORY_CHANGE','COMMENT','CSAT'))
);
CREATE INDEX TICKET_HISTORY_TKT_IX ON TICKET_HISTORY (TICKET_ID);
