--------------------------------------------------------------------------------
-- 01_schema.sql  —  Multi-tenant service desk: 7-table core schema (APEX 26.1)
--------------------------------------------------------------------------------
-- Source of truth: docs/ticketing-system-brief.md  (§ data model).
-- Conventions honoured here:
--   * UPPER_SNAKE_CASE objects; IDENTITY primary keys.
--   * TIMESTAMP WITH LOCAL TIME ZONE on every timestamp (enables aging/FRT/SLA
--     metrics with no schema change — brief §data-model rule 1).
--   * TICKET_HISTORY.action is a fixed enum, not free text (rule 3).
--   * TICKETS.company_id is THE tenant key — every client-facing query filters it.
-- Run order: 00_drop_all (optional reset) -> 01_schema -> 02_seed_data.
--------------------------------------------------------------------------------

-- Sequence that feeds the human-readable ticket reference (TKT-00001, ...).
CREATE SEQUENCE TICKET_REF_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

--------------------------------------------------------------------------------
-- COMPANIES — the vendor company plus every client (tenant).
--------------------------------------------------------------------------------
CREATE TABLE COMPANIES (
  COMPANY_ID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  COMPANY_NAME  VARCHAR2(200)  NOT NULL,
  COMPANY_TYPE  VARCHAR2(10)   NOT NULL,
  STATUS        VARCHAR2(10)   DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT COMPANIES_PK       PRIMARY KEY (COMPANY_ID),
  CONSTRAINT COMPANIES_NAME_UK  UNIQUE (COMPANY_NAME),
  CONSTRAINT COMPANIES_TYPE_CK  CHECK (COMPANY_TYPE IN ('VENDOR','CLIENT')),
  CONSTRAINT COMPANIES_STAT_CK  CHECK (STATUS IN ('ACTIVE','INACTIVE'))
);

--------------------------------------------------------------------------------
-- APP_USERS — everyone who logs in; role + company drive access.
--------------------------------------------------------------------------------
CREATE TABLE APP_USERS (
  USER_ID     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  COMPANY_ID  NUMBER         NOT NULL,
  FULL_NAME   VARCHAR2(200)  NOT NULL,
  EMAIL       VARCHAR2(255)  NOT NULL,
  ROLE        VARCHAR2(20)   NOT NULL,
  STATUS      VARCHAR2(10)   DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT APP_USERS_PK       PRIMARY KEY (USER_ID),
  CONSTRAINT APP_USERS_EMAIL_UK UNIQUE (EMAIL),
  CONSTRAINT APP_USERS_COMP_FK  FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES (COMPANY_ID),
  CONSTRAINT APP_USERS_ROLE_CK  CHECK (ROLE IN ('CLIENT_USER','CLIENT_ADMIN','SUPPORT_AGENT','SYSTEM_ADMIN')),
  CONSTRAINT APP_USERS_STAT_CK  CHECK (STATUS IN ('ACTIVE','INACTIVE'))
);
CREATE INDEX APP_USERS_COMP_IX ON APP_USERS (COMPANY_ID);

--------------------------------------------------------------------------------
-- CATEGORIES — ticket types (Bug, Request, Question, ...).
--------------------------------------------------------------------------------
CREATE TABLE CATEGORIES (
  CATEGORY_ID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  CATEGORY_NAME  VARCHAR2(100) NOT NULL,
  CONSTRAINT CATEGORIES_PK      PRIMARY KEY (CATEGORY_ID),
  CONSTRAINT CATEGORIES_NAME_UK UNIQUE (CATEGORY_NAME)
);

--------------------------------------------------------------------------------
-- AGENT_COMPANIES — which clients each support agent covers (decision I).
-- Scopes an agent's queue to their assigned projects. Composite PK.
--------------------------------------------------------------------------------
CREATE TABLE AGENT_COMPANIES (
  USER_ID     NUMBER NOT NULL,
  COMPANY_ID  NUMBER NOT NULL,
  CONSTRAINT AGENT_COMPANIES_PK   PRIMARY KEY (USER_ID, COMPANY_ID),
  CONSTRAINT AGENT_COMPANIES_U_FK FOREIGN KEY (USER_ID)    REFERENCES APP_USERS (USER_ID),
  CONSTRAINT AGENT_COMPANIES_C_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES (COMPANY_ID)
);
CREATE INDEX AGENT_COMPANIES_C_IX ON AGENT_COMPANIES (COMPANY_ID);

--------------------------------------------------------------------------------
-- TICKETS — the support requests. company_id is the tenant key.
--------------------------------------------------------------------------------
CREATE TABLE TICKETS (
  TICKET_ID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  TICKET_REF   VARCHAR2(20)   NOT NULL,
  COMPANY_ID   NUMBER         NOT NULL,
  SUBJECT      VARCHAR2(300)  NOT NULL,
  DESCRIPTION  CLOB,
  CATEGORY_ID  NUMBER,
  PRIORITY     VARCHAR2(10)   DEFAULT 'Medium' NOT NULL,
  STATUS       VARCHAR2(20)   DEFAULT 'New'    NOT NULL,
  CREATED_BY   NUMBER         NOT NULL,
  ASSIGNED_TO  NUMBER,
  CREATED_AT   TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT   TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  RESOLVED_AT  TIMESTAMP WITH LOCAL TIME ZONE,
  CLOSED_AT    TIMESTAMP WITH LOCAL TIME ZONE,
  SLA_DUE      TIMESTAMP WITH LOCAL TIME ZONE,
  CSAT_SCORE   NUMBER,
  CONSTRAINT TICKETS_PK        PRIMARY KEY (TICKET_ID),
  CONSTRAINT TICKETS_REF_UK    UNIQUE (TICKET_REF),
  CONSTRAINT TICKETS_COMP_FK   FOREIGN KEY (COMPANY_ID)  REFERENCES COMPANIES (COMPANY_ID),
  CONSTRAINT TICKETS_CAT_FK    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (CATEGORY_ID),
  CONSTRAINT TICKETS_CBY_FK    FOREIGN KEY (CREATED_BY)  REFERENCES APP_USERS (USER_ID),
  CONSTRAINT TICKETS_ATO_FK    FOREIGN KEY (ASSIGNED_TO) REFERENCES APP_USERS (USER_ID),
  CONSTRAINT TICKETS_PRIO_CK   CHECK (PRIORITY IN ('Low','Medium','High','Critical')),
  CONSTRAINT TICKETS_STAT_CK   CHECK (STATUS IN ('New','Assigned','In Progress','On Hold','Resolved','Closed')),
  CONSTRAINT TICKETS_CSAT_CK   CHECK (CSAT_SCORE BETWEEN 1 AND 5)
);
CREATE INDEX TICKETS_COMP_IX   ON TICKETS (COMPANY_ID);
CREATE INDEX TICKETS_ATO_IX    ON TICKETS (ASSIGNED_TO);
CREATE INDEX TICKETS_STATUS_IX ON TICKETS (STATUS);

-- Auto-populate the human-readable reference on insert (TKT-00001, ...).
CREATE OR REPLACE TRIGGER TICKETS_REF_BI
  BEFORE INSERT ON TICKETS
  FOR EACH ROW
  WHEN (NEW.TICKET_REF IS NULL)
BEGIN
  :NEW.TICKET_REF := 'TKT-' || LPAD(TICKET_REF_SEQ.NEXTVAL, 5, '0');
END;
/

--------------------------------------------------------------------------------
-- TICKET_COMMENTS — the conversation. is_internal hides agent notes from clients.
--------------------------------------------------------------------------------
CREATE TABLE TICKET_COMMENTS (
  COMMENT_ID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  TICKET_ID     NUMBER NOT NULL,
  USER_ID       NUMBER NOT NULL,
  COMMENT_TEXT  CLOB   NOT NULL,
  IS_INTERNAL   CHAR(1) DEFAULT 'N' NOT NULL,
  CREATED_AT    TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT TICKET_COMMENTS_PK      PRIMARY KEY (COMMENT_ID),
  CONSTRAINT TICKET_COMMENTS_TKT_FK  FOREIGN KEY (TICKET_ID) REFERENCES TICKETS (TICKET_ID),
  CONSTRAINT TICKET_COMMENTS_USR_FK  FOREIGN KEY (USER_ID)   REFERENCES APP_USERS (USER_ID),
  CONSTRAINT TICKET_COMMENTS_INT_CK  CHECK (IS_INTERNAL IN ('Y','N'))
);
CREATE INDEX TICKET_COMMENTS_TKT_IX ON TICKET_COMMENTS (TICKET_ID);

--------------------------------------------------------------------------------
-- TICKET_HISTORY — audit trail. action is a FIXED enum (brief rule 3).
--------------------------------------------------------------------------------
CREATE TABLE TICKET_HISTORY (
  HISTORY_ID   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  TICKET_ID    NUMBER NOT NULL,
  USER_ID      NUMBER,
  ACTION       VARCHAR2(20) NOT NULL,
  OLD_VALUE    VARCHAR2(200),
  NEW_VALUE    VARCHAR2(200),
  CREATED_AT   TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT TICKET_HISTORY_PK      PRIMARY KEY (HISTORY_ID),
  CONSTRAINT TICKET_HISTORY_TKT_FK  FOREIGN KEY (TICKET_ID) REFERENCES TICKETS (TICKET_ID),
  CONSTRAINT TICKET_HISTORY_USR_FK  FOREIGN KEY (USER_ID)   REFERENCES APP_USERS (USER_ID),
  CONSTRAINT TICKET_HISTORY_ACT_CK  CHECK (ACTION IN
      ('STATUS_CHANGE','ASSIGN','ESCALATE','PRIORITY_CHANGE','COMMENT','CSAT'))
);
CREATE INDEX TICKET_HISTORY_TKT_IX ON TICKET_HISTORY (TICKET_ID);
