--------------------------------------------------------------------------------
-- 03_attachments.sql  —  TICKET_ATTACHMENTS (FR-25, COULD feature)
--------------------------------------------------------------------------------
-- Files / screenshots attached to a ticket (or a comment) as evidence.
-- Source of truth: docs/ticketing-system-brief.md §5.1 (build-ready DDL + isolation).
-- Run AFTER 01_schema.sql (references TICKETS, COMPANIES, TICKET_COMMENTS).
--
-- ISOLATION-CRITICAL: COMPANY_ID is denormalized onto every row (copied from the
-- parent ticket at upload) so the declarative "Download BLOB" fetch can filter
-- WHERE COMPANY_ID = :APP_COMPANY_ID without a join — closing the IDOR gap on
-- file downloads. Do NOT drop this column. Run the tenant-isolation-auditor over
-- the attachment region SQL + every download path before demoing (brief §5.1).
--------------------------------------------------------------------------------
CREATE TABLE TICKET_ATTACHMENTS (
  ATTACHMENT_ID  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  TICKET_ID      NUMBER        NOT NULL,
  COMPANY_ID     NUMBER        NOT NULL,   -- tenant key, copied from the ticket at upload
  COMMENT_ID     NUMBER,                   -- null = ticket-level attachment
  FILE_NAME      VARCHAR2(255) NOT NULL,
  MIME_TYPE      VARCHAR2(255),
  FILE_BLOB      BLOB,
  UPLOADED_BY    VARCHAR2(255) DEFAULT SYS_CONTEXT('APEX$SESSION','APP_USER'),
  UPLOADED_AT    TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT TICKET_ATTACH_PK       PRIMARY KEY (ATTACHMENT_ID),
  CONSTRAINT TICKET_ATTACH_TKT_FK   FOREIGN KEY (TICKET_ID)  REFERENCES TICKETS (TICKET_ID),
  CONSTRAINT TICKET_ATTACH_COMP_FK  FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES (COMPANY_ID),
  CONSTRAINT TICKET_ATTACH_CMT_FK   FOREIGN KEY (COMMENT_ID) REFERENCES TICKET_COMMENTS (COMMENT_ID)
);
CREATE INDEX TICKET_ATTACH_TICKET_IX  ON TICKET_ATTACHMENTS (TICKET_ID);
CREATE INDEX TICKET_ATTACH_COMPANY_IX ON TICKET_ATTACHMENTS (COMPANY_ID);

--------------------------------------------------------------------------------
-- Belt-and-braces: keep COMPANY_ID honest. Even though the APEX upload process
-- sets it, this trigger guarantees the row's tenant key always matches its
-- parent ticket — so a bad insert can never mis-tag a file to the wrong tenant.
--------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TICKET_ATTACH_COMP_BI
  BEFORE INSERT ON TICKET_ATTACHMENTS
  FOR EACH ROW
BEGIN
  SELECT COMPANY_ID INTO :NEW.COMPANY_ID
  FROM   TICKETS
  WHERE  TICKET_ID = :NEW.TICKET_ID;
END;
/
